Feature/models
Evgenia789/task-manager pull request #5
Opened 2023-04-19 12:45 UTC by Evgenia789

Урок 5.2. Реализация моделей

2023-04-19 17:57 UTC, aleksandr-semenov-dbp requested changes

2023-04-19 17:57 UTC, aleksandr-semenov-dbp commented on main/models/tag.py
> +    uniq_id = models.CharField(max_length=200, null=True, blank=False)
Не очень понятно зачем это поле? id и так есть автоматом, а сюда придется видимо что-то генерировать, вдобавок никаких констрейнтов в базе на уникальность не предусмотрено

2023-04-20 06:30 UTC, Evgenia789 commented on main/models/tag.py
> +    uniq_id = models.CharField(max_length=200, null=True, blank=False)
Убрала. В задании, в описании модели Тег, это поле как-то отдельно было выделено, я подумала, что оно понадобится потом.

2023-04-20 12:15 UTC, aleksandr-semenov-dbp requested changes

2023-04-21 10:50 UTC, aleksandr-semenov-dbp approved these changes

2023-04-21 11:14 UTC, merged